apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
  labels:
    app: calculator-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator-deployment
  template:
    metadata:
      labels:
        app: calculator-deployment
    spec:
      containers:
      - name: calculator
        image: dhineshdine/cal-demo-jenkins:01
        ports:
        - containerPort: 5000
